version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: reallyStrongPwd123
      MSSQL_PID: Developer
      MSSQL_USER: sa
    ports:
      - "1433:1433"
